apiVersion: apps/v1
kind: Deployment
metadata:
  name: hunter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hunter
  template:
    metadata:
      labels:
        app: hunter
    spec:
      serviceAccountName: hunter-k8s-sa
      containers:
      - name: hunter
        image: us.gcr.io/ps5hunter/hunter:latest
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: hunter-config
            mountPath: "/hunter/config"
            readOnly: true
        env:
          - name: TWILIO_FROM_NUM
            valueFrom:
              secretKeyRef:
                name: twilio
                key: TWILIO_FROM_NUM
          - name: TWILIO_ACCOUNT_SID
            valueFrom:
              secretKeyRef:
                name: twilio
                key: TWILIO_ACCOUNT_SID
          - name: TWILIO_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: twilio
                key: TWILIO_AUTH_TOKEN
          - name: SMS_NOTIFY_NUM
            valueFrom:
              secretKeyRef:
                name: twilio
                key: SMS_NOTIFY_NUM
          - name: TWITTER_API_KEY
            valueFrom:
              secretKeyRef:
                name: twitter
                key: TWITTER_API_KEY
          - name: TWITTER_API_SECRET
            valueFrom:
              secretKeyRef:
                name: twitter
                key: TWITTER_API_SECRET
          - name: SELENIUM_URL
            valueFrom:
              configMapKeyRef:
                name: hunter-config
                key: SELENIUM_URL
      volumes:
        - name: hunter-config
          configMap:
            name: hunter-config